### PR TITLE
Trevmoy patch 2

### PR DESCRIPTION
**Pull request by trevmoy**
Sorry if this is not the way I should propose changes. This is my first attempt at making a community/explore badge.

### CODE REVIEW

**Comment by brownsarahm** [comment]
this PR is from a branch within your fork to a different branch wihtin your fork. first step is to make to compare across forks.

**Comment by trevmoy** [comment]
@brownsarahm Did you mean this? I don't really know what you mean by comparing across forks.

**Comment by brownsarahm** [comment]
you can't edit this PR to be that way, but when you make a new PR there is the option to compare across forks. [docs](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by brownsarahm** [comment]
can we close this one?

**Pull request closed without merging**
